import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/shared/Navbar";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});


export const metadata = {
  title: "MediQueue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
