import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import Footer from "@/components/shared/Footer";
import TitleUpdater from "@/components/shared/TitleUpdater";
import { Toaster } from "react-hot-toast";
import NextThemeProvider from "@/providers/NextThemeProvider";

const poppins = Poppins({
  weight: "400",
  subsets: ["latin"],
});


export const metadata = {
  title: "MediQueue",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${poppins.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-background text-foreground">
        <NextThemeProvider>
          <TitleUpdater />
          <Navbar />
          {children}
          <Footer />
          <Toaster />
        </NextThemeProvider>
      </body>
    </html>
  );
}
